#!/usr/bin/env python3
"""Generate the C header and Python module from protocol/schema.py.

    python protocol/generate.py          # write files
    python protocol/generate.py --check  # exit 1 if outputs are stale (CI)
"""
import hashlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import schema as S  # noqa: E402

ROOT = os.path.dirname(HERE)
OUT_PY = os.path.join(HERE, "generated", "vaic_protocol.py")
OUT_H = os.path.join(HERE, "generated", "vaic_protocol.h")
# Every V5 project that should receive a copy of the header.
V5_HEADER_COPIES = [
    os.path.join(ROOT, "v5", "robot", "include", "vaic_protocol.h"),
]
BANNER = "GENERATED by protocol/generate.py from protocol/schema.py. DO NOT EDIT."


def layout_hash() -> str:
    return hashlib.sha256(S.canonical_layout().encode()).hexdigest()[:12]


def struct_fmt(name: str) -> str:
    """Little-endian struct format for one struct, arrays expanded."""
    if name in S.SCALARS:
        return S.SCALARS[name][1]
    out = ""
    for f in S.struct_by_name(name).fields:
        out += struct_fmt(f.type) * (f.array or 1)
    return out


def gen_c() -> str:
    h = layout_hash()
    L = [f"/* {BANNER} */",
         f"/* layout hash {h} */",
         "#ifndef VAIC_PROTOCOL_H_", "#define VAIC_PROTOCOL_H_", "",
         "#include <stdint.h>", "",
         "#ifdef __cplusplus", 'extern "C" {', "#endif", "",
         f"#define VAIC_PROTOCOL_VERSION   {S.PROTOCOL_VERSION}",
         f'#define VAIC_LAYOUT_HASH        "{h}"',
         f"#define MAX_DETECTIONS          {S.MAX_DETECTIONS}",
         f"#define VAIC_BAUD               {S.BAUD}",
         "#define VAIC_SYNC_BYTES         {{ {} }}".format(", ".join(f"0x{b:02X}" for b in S.SYNC_BYTES)),
         f"#define VAIC_CRC32_POLY         0x{S.CRC32_POLY:08X}", ""]
    for k, (v, c) in S.PACKET_TYPES.items():
        L.append(f"#define {k:<28}0x{v:04X}  /* {c} */")
    L.append("")
    for k, v in S.POS_STATUS_FLAGS.items():
        L.append(f"#define {k:<28}0x{v:08X}")
    for k, v in S.ODOM_STATUS_FLAGS.items():
        L.append(f"#define {k:<28}0x{v:08X}")
    L.append("")
    for s in S.STRUCTS:
        L.append(f"/** {s.comment} */")
        L.append("typedef struct __attribute__((__packed__)) {")
        for f in s.fields:
            ctype = S.SCALARS[f.type][0] if f.type in S.SCALARS else f.type
            decl = f"{f.name}[{f.array}]" if f.array else f.name
            comment = f"  /* {f.comment} */" if f.comment else ""
            L.append(f"    {ctype:<18}{decl};{comment}")
        L.append(f"}} {s.name};")
        L.append(f"#define {s.name}_SIZE {S.size_of(s.name)}")
        L.append("")
    L += ["/* Packet header that precedes every payload on the serial link. */",
          "typedef struct __attribute__((__packed__)) {",
          "    uint8_t     sync[4];",
          "    uint16_t    length;   /* payload bytes, header excluded */",
          "    uint16_t    type;     /* PACKET_TYPE_* */",
          "    uint32_t    crc32;    /* CRC of payload */",
          "} VAIC_PACKET_HEADER;",
          "#define VAIC_PACKET_HEADER_SIZE 12", "",
          "/* Compatibility with VEX ai_jetson.h */",
          "#define MAP_POS_SIZE   (sizeof(int32_t) + sizeof(POS_RECORD))",
          "#define MAP_PACKET_TYPE PACKET_TYPE_AI_RECORD", "",
          "#ifdef __cplusplus", "}", "",
          "/* Compile-time guard: fails if the compiler disagrees with the generator. */"]
    for s in S.STRUCTS:
        L.append(f'static_assert(sizeof({s.name}) == {s.name}_SIZE, "{s.name} size mismatch");')
    L.append('static_assert(sizeof(VAIC_PACKET_HEADER) == VAIC_PACKET_HEADER_SIZE, "header size mismatch");')
    L += ["#endif", "", "#endif /* VAIC_PROTOCOL_H_ */", ""]
    return "\n".join(L)


def gen_py() -> str:
    h = layout_hash()
    L = [f'"""{BANNER}', f"layout hash {h}", '"""',
         "from __future__ import annotations",
         "import struct",
         "from dataclasses import dataclass, field",
         "from typing import List, Tuple", "",
         f"PROTOCOL_VERSION = {S.PROTOCOL_VERSION}",
         f'LAYOUT_HASH = "{h}"',
         f"MAX_DETECTIONS = {S.MAX_DETECTIONS}",
         f"SYNC_BYTES = bytes({list(S.SYNC_BYTES)})",
         f"BAUD = {S.BAUD}",
         f'REQUEST_LINE = "{S.REQUEST_LINE}"',
         f"CRC32_POLY = 0x{S.CRC32_POLY:08X}",
         'HEADER_FMT = "<4sHHI"',
         "HEADER_SIZE = struct.calcsize(HEADER_FMT)", ""]
    for k, (v, c) in S.PACKET_TYPES.items():
        L.append(f"{k} = 0x{v:04X}  # {c}")
    L.append("")
    for k, v in S.POS_STATUS_FLAGS.items():
        L.append(f"{k} = 0x{v:08X}")
    for k, v in S.ODOM_STATUS_FLAGS.items():
        L.append(f"{k} = 0x{v:08X}")
    L.append("")

    for s in S.STRUCTS:
        fmt = "<" + struct_fmt(s.name)
        L.append("@dataclass")
        L.append(f"class {s.name}:")
        L.append(f'    """{s.comment}"""')
        for f in s.fields:
            if f.array:
                L.append(f"    {f.name}: List[{f.type}] = field(default_factory=list)")
            elif f.type in S.SCALARS:
                py = "int" if f.type in ("i32", "u32") else "float"
                default = "0" if py == "int" else "0.0"
                L.append(f"    {f.name}: {py} = {default}")
            else:
                L.append(f"    {f.name}: {f.type} = field(default_factory=lambda: {f.type}())")
        L.append("")
        L.append(f'    FMT = "{fmt}"')
        L.append(f"    SIZE = {S.size_of(s.name)}")
        if s.count_field:
            arr = [f for f in s.fields if f.array][0]
            fixed = [f for f in s.fields if not f.array]
            fixed_fmt = "<" + "".join(struct_fmt(f.type) for f in fixed)
            L.append(f'    FIXED_FMT = "{fixed_fmt}"')
            L.append(f"    FIXED_SIZE = {sum(S.size_of(f.type) for f in fixed)}")
            L.append("")
            L.append("    def pack(self) -> bytes:")
            L.append(f'        """Variable-length: only {arr.name}[:{s.count_field}] are sent."""')
            L.append(f"        n = min(len(self.{arr.name}), MAX_DETECTIONS)")
            L.append(f"        self.{s.count_field} = n")
            L.append("        out = bytearray(self._pack_fixed())")
            L.append(f"        for d in self.{arr.name}[:n]:")
            L.append("            out += d.pack()")
            L.append("        return bytes(out)")
            L.append("")
            L.append("    def _pack_fixed(self) -> bytes:")
            L.append("        return struct.pack(self.FIXED_FMT, *self._flat_fixed())")
            L.append("")
            L.append("    def _flat_fixed(self) -> list:")
            L.append("        out = []")
            for f in fixed:
                if f.type in S.SCALARS:
                    L.append(f"        out.append(self.{f.name})")
                else:
                    L.append(f"        out += self.{f.name}._flat()")
            L.append("        return out")
            L.append("")
            L.append("    @classmethod")
            L.append(f"    def unpack(cls, data: bytes) -> '{s.name}':")
            L.append("        vals = list(struct.unpack_from(cls.FIXED_FMT, data, 0))")
            L.append("        obj = cls()")
            L.append("        i = 0")
            for f in fixed:
                if f.type in S.SCALARS:
                    L.append(f"        obj.{f.name} = vals[i]; i += 1")
                else:
                    L.append(f"        obj.{f.name} = {f.type}._from_flat(vals[i:i + {f.type}.NFIELDS]); i += {f.type}.NFIELDS")
            L.append(f"        n = obj.{s.count_field}")
            L.append("        if n < 0 or n > MAX_DETECTIONS:")
            L.append(f'            raise ValueError(f"bad {s.count_field} {{n}}")')
            L.append(f"        need = cls.FIXED_SIZE + n * {arr.type}.SIZE")
            L.append("        if len(data) < need:")
            L.append('            raise ValueError(f"payload too short: {len(data)} < {need}")')
            L.append("        off = cls.FIXED_SIZE")
            L.append(f"        obj.{arr.name} = [{arr.type}.unpack(data[off + k * {arr.type}.SIZE: off + (k + 1) * {arr.type}.SIZE]) for k in range(n)]")
            L.append("        return obj")
        else:
            nfields = len(struct_fmt(s.name))
            L.append(f"    NFIELDS = {nfields}")
            L.append("")
            L.append("    def _flat(self) -> list:")
            L.append("        out = []")
            for f in s.fields:
                if f.type in S.SCALARS:
                    L.append(f"        out.append(self.{f.name})")
                else:
                    L.append(f"        out += self.{f.name}._flat()")
            L.append("        return out")
            L.append("")
            L.append("    @classmethod")
            L.append(f"    def _from_flat(cls, vals) -> '{s.name}':")
            L.append("        obj = cls()")
            L.append("        i = 0")
            for f in s.fields:
                if f.type in S.SCALARS:
                    L.append(f"        obj.{f.name} = vals[i]; i += 1")
                else:
                    L.append(f"        obj.{f.name} = {f.type}._from_flat(vals[i:i + {f.type}.NFIELDS]); i += {f.type}.NFIELDS")
            L.append("        return obj")
            L.append("")
            L.append("    def pack(self) -> bytes:")
            L.append("        return struct.pack(self.FMT, *self._flat())")
            L.append("")
            L.append("    @classmethod")
            L.append(f"    def unpack(cls, data: bytes) -> '{s.name}':")
            L.append("        return cls._from_flat(struct.unpack(cls.FMT, data[:cls.SIZE]))")
        L.append("")
        L.append("")

    L += [
        "_CRC_TABLE = None", "",
        "def crc32(data: bytes, acc: int = 0) -> int:",
        '    """Non-reflected CRC-32 (poly 0x04C11DB7, init 0), identical to VEX V5Comm.py."""',
        "    global _CRC_TABLE",
        "    if _CRC_TABLE is None:",
        "        t = []",
        "        for i in range(256):",
        "            c = i << 24",
        "            for _ in range(8):",
        "                c = ((c << 1) ^ CRC32_POLY) if c & 0x80000000 else (c << 1)",
        "            t.append(c & 0xFFFFFFFF)",
        "        _CRC_TABLE = t",
        "    for b in data:",
        "        acc = ((acc << 8) ^ _CRC_TABLE[((acc >> 24) ^ b) & 0xFF]) & 0xFFFFFFFF",
        "    return acc", "", "",
        "def build_packet(payload: bytes, packet_type: int) -> bytes:",
        '    """sync(4) + length(2) + type(2) + crc32(4) + payload."""',
        "    return struct.pack(HEADER_FMT, SYNC_BYTES, len(payload), packet_type, crc32(payload)) + payload", "", "",
        "def parse_packet(data: bytes) -> Tuple[int, bytes]:",
        '    """Return (type, payload) or raise ValueError. Used by tests and log replay."""',
        "    if len(data) < HEADER_SIZE:",
        '        raise ValueError("short header")',
        "    sync, length, ptype, crc = struct.unpack_from(HEADER_FMT, data, 0)",
        "    if sync != SYNC_BYTES:",
        '        raise ValueError("bad sync")',
        "    payload = data[HEADER_SIZE:HEADER_SIZE + length]",
        "    if len(payload) != length:",
        '        raise ValueError("short payload")',
        "    if crc32(payload) != crc:",
        '        raise ValueError("crc mismatch")',
        "    return ptype, payload", "", "",
        "def encode_ai_record(rec: AI_RECORD) -> bytes:",
        "    return build_packet(rec.pack(), PACKET_TYPE_AI_RECORD)", "", "",
        "def decode_ai_record(data: bytes) -> AI_RECORD:",
        "    ptype, payload = parse_packet(data)",
        "    if ptype != PACKET_TYPE_AI_RECORD:",
        '        raise ValueError(f"unexpected packet type 0x{ptype:04X}")',
        "    return AI_RECORD.unpack(payload)", "",
    ]
    return "\n".join(L)


def main() -> int:
    outputs = {OUT_PY: gen_py(), OUT_H: gen_c()}
    for p in V5_HEADER_COPIES:
        outputs[p] = outputs[OUT_H]
    check = "--check" in sys.argv
    stale = []
    for path, text in outputs.items():
        current = open(path).read() if os.path.exists(path) else None
        if current == text:
            continue
        if check:
            stale.append(path)
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w") as f:
                f.write(text)
            print("wrote", os.path.relpath(path, ROOT))
    if stale:
        print("STALE (run python protocol/generate.py):")
        for p in stale:
            print("  ", os.path.relpath(p, ROOT))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
