/* GENERATED by protocol/generate.py from protocol/schema.py. DO NOT EDIT. */
/* layout hash cae69d2ab237 */
#ifndef VAIC_PROTOCOL_H_
#define VAIC_PROTOCOL_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define VAIC_PROTOCOL_VERSION   1
#define VAIC_LAYOUT_HASH        "cae69d2ab237"
#define MAX_DETECTIONS          50
#define VAIC_BAUD               115200
#define VAIC_SYNC_BYTES         { 0xAA, 0x55, 0xCC, 0x33 }
#define VAIC_CRC32_POLY         0x04C11DB7

#define PACKET_TYPE_AI_RECORD       0x0001  /* AI_RECORD payload, layout v1 */

#define POS_STATUS_CONNECTED        0x00000001
#define POS_STATUS_NODOTS           0x00000002
#define POS_STATUS_NORAWBITS        0x00000004
#define POS_STATUS_NOGROUPS         0x00000008
#define POS_STATUS_NOBITS           0x00000010
#define POS_STATUS_PIXELERROR       0x00000020
#define POS_STATUS_SOLVER           0x00000040
#define POS_STATUS_ANGLEJUMP        0x00000080
#define POS_STATUS_POSJUMP          0x00000100
#define POS_STATUS_NOSOLUTION       0x00000200
#define POS_STATUS_KALMAN_EST       0x00100000

/** Robot pose from the V5 GPS sensor, offsets already applied */
typedef struct __attribute__((__packed__)) {
    int32_t           framecnt;  /* Increments each GPS frame */
    int32_t           status;  /* 0 = good; see POS_STATUS_* flags */
    float             x;  /* Field X in meters, 0 at field center */
    float             y;  /* Field Y in meters, 0 at field center */
    float             z;  /* Height above tiles in meters */
    float             az;  /* Heading in degrees */
    float             el;  /* Pitch in degrees */
    float             rot;  /* Roll in degrees */
} POS_RECORD;
#define POS_RECORD_SIZE 32

/** Detection in camera image coordinates */
typedef struct __attribute__((__packed__)) {
    int32_t           x;  /* Bounding box center X in pixels, 0 at top-left */
    int32_t           y;  /* Bounding box center Y in pixels */
    int32_t           width;  /* Bounding box width in pixels */
    int32_t           height;  /* Bounding box height in pixels */
} IMAGE_DETECTION;
#define IMAGE_DETECTION_SIZE 16

/** Detection in field coordinates */
typedef struct __attribute__((__packed__)) {
    float             x;  /* Field X in meters */
    float             y;  /* Field Y in meters */
    float             z;  /* Height above tiles in meters */
} MAP_DETECTION;
#define MAP_DETECTION_SIZE 12

/** One detected object */
typedef struct __attribute__((__packed__)) {
    int32_t           classID;  /* Index into labels.txt */
    float             probability;  /* Confidence, 1.0 == 100% */
    float             depth;  /* Distance from camera in meters */
    IMAGE_DETECTION   screenLocation;
    MAP_DETECTION     mapLocation;
} DETECTION_OBJECT;
#define DETECTION_OBJECT_SIZE 40

/** Everything the coprocessor sends per frame */
typedef struct __attribute__((__packed__)) {
    int32_t           detectionCount;  /* Number of valid entries in detections[] */
    POS_RECORD        pos;
    DETECTION_OBJECT  detections[50];
} AI_RECORD;
#define AI_RECORD_SIZE 2036

/* Packet header that precedes every payload on the serial link. */
typedef struct __attribute__((__packed__)) {
    uint8_t     sync[4];
    uint16_t    length;   /* payload bytes, header excluded */
    uint16_t    type;     /* PACKET_TYPE_* */
    uint32_t    crc32;    /* CRC of payload */
} VAIC_PACKET_HEADER;
#define VAIC_PACKET_HEADER_SIZE 12

/* Compatibility with VEX ai_jetson.h */
#define MAP_POS_SIZE   (sizeof(int32_t) + sizeof(POS_RECORD))
#define MAP_PACKET_TYPE PACKET_TYPE_AI_RECORD

#ifdef __cplusplus
}

/* Compile-time guard: fails if the compiler disagrees with the generator. */
static_assert(sizeof(POS_RECORD) == POS_RECORD_SIZE, "POS_RECORD size mismatch");
static_assert(sizeof(IMAGE_DETECTION) == IMAGE_DETECTION_SIZE, "IMAGE_DETECTION size mismatch");
static_assert(sizeof(MAP_DETECTION) == MAP_DETECTION_SIZE, "MAP_DETECTION size mismatch");
static_assert(sizeof(DETECTION_OBJECT) == DETECTION_OBJECT_SIZE, "DETECTION_OBJECT size mismatch");
static_assert(sizeof(AI_RECORD) == AI_RECORD_SIZE, "AI_RECORD size mismatch");
static_assert(sizeof(VAIC_PACKET_HEADER) == VAIC_PACKET_HEADER_SIZE, "header size mismatch");
#endif

#endif /* VAIC_PROTOCOL_H_ */
